### ISSUE TITLE
Seems nested jar are signed when they shouldn't be

### ISSUE THREAD

**Issue by fbricon** [eclipse-cbi/org.eclipse.cbi#462]
eclipse-jarsigner:1.4.3 detects nested jar signing is disabled, proceed to sign anyway, wasting several seconds on each jar, in [jdt.ls](https://github.com/eclipse-jdtls/eclipse.jdt.ls/blob/master/pom.xml#L115-L128):

```
15:12:25 [INFO] --- eclipse-jarsigner:1.4.3:sign (sign) @ org.eclipse.jdt.ls.core ---
15:12:26 [INFO] Signing of nested jars of '/home/jenkins/agent/workspace/jdt-ls-master/org.eclipse.jdt.ls.core/target/org.eclipse.jdt.ls.core-1.36.0-SNAPSHOT.jar_unpacked_9725347443788748573/lib/remark-1.2.0.jar' is disabled.
15:12:26 [INFO] Signing jar: /home/jenkins/agent/workspace/jdt-ls-master/org.eclipse.jdt.ls.core/target/org.eclipse.jdt.ls.core-1.36.0-SNAPSHOT.jar_unpacked_9725347443788748573/lib/remark-1.2.0.jar
15:12:31 [INFO] Signing of nested jars of '/home/jenkins/agent/workspace/jdt-ls-master/org.eclipse.jdt.ls.core/target/org.eclipse.jdt.ls.core-1.36.0-SNAPSHOT.jar_unpacked_9725347443788748573/lib/jsoup-1.14.2.jar' is disabled.
15:12:31 [INFO] Signing jar: /home/jenkins/agent/workspace/jdt-ls-master/org.eclipse.jdt.ls.core/target/org.eclipse.jdt.ls.core-1.36.0-SNAPSHOT.jar_unpacked_9725347443788748573/lib/jsoup-1.14.2.jar
15:12:34 [INFO] Signing of nested jars of '/home/jenkins/agent/workspace/jdt-ls-master/org.eclipse.jdt.ls.core/target/org.eclipse.jdt.ls.core-1.36.0-SNAPSHOT.jar_unpacked_9725347443788748573/lib/java-decompiler-engine-231.9011.34.jar' is disabled.
15:12:34 [INFO] Signing jar: /home/jenkins/agent/workspace/jdt-ls-master/org.eclipse.jdt.ls.core/target/org.eclipse.jdt.ls.core-1.36.0-SNAPSHOT.jar_unpacked_9725347443788748573/lib/java-decompiler-engine-231.9011.34.jar
15:12:39 [INFO] Signing jar: /home/jenkins/agent/workspace/jdt-ls-master/org.eclipse.jdt.ls.core/target/org.eclipse.jdt.ls.core-1.36.0-SNAPSHOT.jar
15:12:44 [INFO] Signing jar: /home/jenkins/agent/workspace/jdt-ls-master/org.eclipse.jdt.ls.core/target/org.eclipse.jdt.ls.core-1.36.0-SNAPSHOT-sources.jar
15:12:48 [INFO] 
15:12:48 [INFO] --- tycho-p2:4.0.8:p2-metadata (p2-metadata) @ org.eclipse.jdt.ls.core ---
```

See https://ci.eclipse.org/ls/job/jdt-ls-master/2021/console

It's even worse with our test plugin (see 6 minute step starting at 15:13:35)

**Comment by netomi** [comment]
I think that is a misunderstanding how signing of nested jars works in the eclipse-jarsigner plugin.

Take a look at the documentation of the excludeInnerJars property at https://github.com/eclipse-cbi/org.eclipse.cbi/blob/main/maven-plugins/eclipse-jarsigner-plugin/src/main/java/org/eclipse/cbi/maven/plugins/jarsigner/mojo/SignMojo.java#L163-L171

By default its set to false, and it means that the first level of nested jars will be signed as well.

In order to avoid signing of nested jars at all, you need to disable that in the configuration of the plugin, like in this case:

https://github.com/eclipse/gef-classic/blob/master/pom.xml#L314

I agree, its confusing, but setting excludeInnerJars to true should resolve your problem imho.

**Comment by netomi** [comment]
So looking at the log, in your project you use the jarsigner plugin with default settings, so the first level of nested jars is signed as well. Thats why you see that the jars are listed, but then not further traversed for nested signing.

I agree that this is a rather weird choice of processing also considering the property name, but it might be necessary in some cases that I am not aware of.

**Comment by mbarbero** [comment]
Good catch. This has been the default behavior for over the last decade, so I would vote against changing it. However, the [log message](https://github.com/eclipse-cbi/org.eclipse.cbi/blob/main/maven-plugins/eclipse-jarsigner-plugin/src/main/java/org/eclipse/cbi/maven/plugins/jarsigner/RecursiveJarSigner.java#L61) could be tweaked for clarity:

Rather than 

```
[INFO] Signing of nested jars of '/home/jenkins/agent/workspace/jdt-ls-master/org.eclipse.jdt.ls.core/target/org.eclipse.jdt.ls.core-1.36.0-SNAPSHOT.jar_unpacked_9725347443788748573/lib/remark-1.2.0.jar' is disabled.
Signing jar: /home/jenkins/agent/workspace/jdt-ls-master/org.eclipse.jdt.ls.core/target/org.eclipse.jdt.ls.core-1.36.0-SNAPSHOT.jar_unpacked_9725347443788748573/lib/remark-1.2.0.jar
```

It could say something like this (also changing logging level to avoid displaying it by default):

```
[DEBUG] Signing of nested jars within '/home/jenkins/agent/workspace/jdt-ls-master/org.eclipse.jdt.ls.core/target/org.eclipse.jdt.ls.core-1.36.0-SNAPSHOT.jar_unpacked_9725347443788748573/lib/remark-1.2.0.jar' is disabled.
Signing jar: /home/jenkins/agent/workspace/jdt-ls-master/org.eclipse.jdt.ls.core/target/org.eclipse.jdt.ls.core-1.36.0-SNAPSHOT.jar_unpacked_9725347443788748573/lib/remark-1.2.0.jar
```

**Comment by netomi** [comment]
Makes sense, I did not have the intention to change anything, but making the logging more descriptive of what is actually happening. Do we also publish the mojo documentation somewhere? That would be helpful I guess.

**Comment by fbricon** [comment]
Yeah the logging statement is definitely confusing. +1 for @mbarbero's proposal

**Comment by netomi** [comment]
fyi: there is now also the maven plugin site deployed to https://eclipse-cbi.github.io/org.eclipse.cbi/ to get more information about the plugins and their configuration.
